rails/config/routes.rb
# Copyright 2013, Dell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
Crowbar::Application.routes.draw do

  # UI scope

  # special case items that allow IDs to have .s 
  constraints(:id => /.*/ ) do
    resources :nodes do
      resources :node_roles
      resources :attribs
    end
  end

  # UI resources (should generally match the API paths)
  get "annealer", :to => "node_roles#anneal", :as => :annealer
  resources :attribs
  resources :barclamps
  resources :deployments do
    get :head
    get :next
    resources :roles
  end
  resources :deployment_roles
  get 'docs', to: 'docs#index'
  get 'docs/:id', to: 'docs#show', constraints: {id: /[^\?]*/}
#  resources :docs
  resources :groups
  resources :jigs
  resources :node_roles  do
    put :retry
  end
  resources :roles
  resources :snapshots do
    resources :node_roles
    get :graph
    put :propose
    put :commit
    put :recall
  end

  namespace :barclamp_network do
    resources :interfaces
    resources :networks do
      get :ranges
      get :routers
      get :allocations
    end
    # special views
    get 'map' => "networks#map", :as=> :network_map
  end

  # UI only functionality to help w/ visualization
  scope 'dashboard' do
    get 'list(/:deployment)'  => 'dashboard#list', :as => :bulk_edit
    put 'list'                => 'dashboard#list', :as => :bulk_edit
    get 'layercake'           => 'dashboard#layercake', :as => :layercake
  end
  
  # UI only functionality to help w/ visualization
  scope 'utils' do
    get '/'             => 'support#index', :as => :utils
    get 'i18n/:id'      => 'support#i18n', :as => :utils_i18n, :constraints => { :id => /.*/ }
    get 'marker/:id'    => 'support#marker', :as => :utils_marker
    get 'files/:id'     => 'support#index', :as => :utils_files
    get 'import(/:id)'  => 'support#import', :as => :utils_import
    get 'upload/:id'    => 'support#upload', :as => :utils_upload
    get 'restart/:id'   => 'support#restart', :as => :restart
    get 'digest'        => "support#digest"
    get 'fail'          => "support#fail"
    match "bootstrap"     => "support#bootstrap", :as => :bootstrap
    namespace :scaffolds do
      resources :attribs do as_routes end
      resources :barclamps do as_routes end
      resources :docs do as_routes end
      resources :deployments do as_routes end
      resources :groups do as_routes end
      resources :jigs do as_routes end
      resources :navs do as_routes end
      resources :nodes do as_routes end
      resources :roles do as_routes end
      resources :role_requires do as_routes end
      resources :runs do as_routes end
      resources :snapshots do as_routes end
      resources :node_roles do as_routes end
      resources :deployment_roles do as_routes end
      resources :networks do as_routes end
      resources :routers do as_routes end
      resources :ranges do as_routes end
      resources :allocations do as_routes end
    end
  end

  # UI scope - legacy methods
  scope 'support' do
    get 'logs', :controller => 'support', :action => 'logs'
    get 'get_cli', :controller => 'support', :action => 'get_cli'
  end

  # these are ok, but really should move to the user resource!
  put 'reset_password(/:id)', :controller => 'users', :action=>"reset_password", :as=>:reset_password
  get 'edit_password/:id', :controller => 'users', :action=>'edit_password', :constraints => { :id => /.*/ }, :as => :edit_password
  delete 'unlock/:id', :controller => 'users', :action=>'unlock', :constraints => { :id => /.*/ }, :as => :unlock
  post 'lock/:id', :controller => 'users', :action=>'lock', :constraints => { :id => /.*/ }, :as => :lock
  match "manage_users", :controller => 'users', :action => 'index'
  match "delete_users", :controller => 'users', :action => 'delete_users', :as=> :delete_users

  devise_for :users, { :path_prefix => 'my', :module => :devise, :class_name=> 'Crowbar::User' }

  get    "/users/new(.:format)", :controller => 'users', :action=>'index', :as=> :new_user
  resources :users, :except => :new

  # API routes (must be json and must prefix v2)()
  scope :defaults => {:format => 'json'} do

    constraints(:id => /([a-zA-Z0-9\-\.\_]*)/, :version => /v[1-9]/) do

      # framework resources pattern (not barclamps specific)
      scope 'api' do
        scope 'status' do
          get "nodes(/:id)" => "nodes#status", :as => :nodes_status
          get "snapshots(/:id)" => "snapshots#status", :as => :snapshots_status
        end
        scope 'test' do
          put "nodes(/:id)" => "nodes#test_load_data"
        end
        scope ':version' do
          # These are not restful.  They poke the annealer and wait if you pass "sync=true".
          get "anneal", :to => "node_roles#anneal", :as => :anneal
          post "make_admin", :to => "nodes#make_admin", :as => :make_admin
          resources :attribs
          resources :barclamps
          resources :deployments do
            get :head
            get :next
            resources :roles
            resources :nodes
            put 'claim/:node_id' => "deployments#claim"
          end
          resources :deployment_roles do
            resources :attribs
          end
          resources :groups do
            member do
              get 'nodes'
            end
          end
          namespace :barclamp_network do
            resources :networks do
              resources :ranges
              resources :routers
              member do
                match 'ip'
                post 'allocate_ip'
                get 'allocations'
              end
            end
          end
          resources :interfaces
          resources :runs
          resources :jigs
          resources :nodes do
            resources :node_roles
            resources :attribs
            resources :roles
            put :reboot
            put :debug
            put :undebug
          end
          resources :node_roles do
            put :retry
          end
          resources :roles do
            resources :deployment_roles
            put 'template/:key/:value' => "roles#template"
          end
          resources :snapshots do
            resources :node_roles
            resources :nodes
            resources :roles
            resources :deployment_roles
            get :graph
            put :propose
            put :commit
            put :recall
          end
          resources :users do
            post "admin", :controller => "users", :action => "make_admin"
            delete "admin", :controller => "users", :action => "remove_admin"
            post "lock", :controller => "users", :action => "lock"
            delete "lock", :controller => "users", :action => "unlock"
            put "reset_password", :controller => "users", :action => "reset_password"
          end
        end # version
      end # api
    end # id constraints
  end # json

  # Install route from each root barclamp (should be done last so CB gets priority)
  begin
    Barclamp.roots.each do |bc|
      eval(IO.read(File.path(bc.source_path, "rails", "config", "routes.rb")), binding) unless bc.name.eql? 'crowbar'
    end
  rescue
    # startup cannot resolve Barclamp
  end

  root :to => 'dashboard#layercake'
end

rails/app/controllers/support_controller.rb
# Copyright 2013, Dell 
# 
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
# 
#  http://www.apache.org/licenses/LICENSE-2.0 
# 
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
# 


class SupportController < ApplicationController

  skip_before_filter :crowbar_auth, :only => :digest
  before_filter :digest_auth!, :only => :digest

  # used to pass a string into the debug logger to help find specificall calls  
  def marker
    Rails.logger.info "\nMARK >>>>> #{params[:id]} <<<<< KRAM\n"
    render :text=>params[:id]
  end

  def digest
    if session[:digest_user]
      render :text => t('user.digest_success', :default=>'success')
    else
      render :text => "digest", :status => :unauthorized
    end
  end

  def fail
    raise I18n.t('chuck_norris')
  end

  # used to lookup localization values
  def i18n
    begin
      render :text=>I18n.translate(params[:id], :raise => I18n::MissingTranslationData)
    rescue I18n::MissingTranslationData
      render :text=>"No translation for #{params[:id]}", :status => 404
    end
  end

  # Legacy Support (UI version moved to loggin barclamp)
  def logs
    @file = "crowbar-logs-#{ctime}.tar.bz2"
    system("sudo -i /opt/dell/bin/gather_logs.sh #{@file}")
    redirect_to "/export/#{@file}"
  end
  
  def get_cli
    system("sudo -i /opt/dell/bin/gather_cli.sh #{request.env['SERVER_ADDR']} #{request.env['SERVER_PORT']}")
    redirect_to "/crowbar-cli.tar.gz"
  end

  def import
    @barclamps = Barclamp.all
  end

  def index
    @waiting = params['waiting'] == 'true'
    remove_file 'export', params[:id] if params[:id]
    @exports = { :count=>0, :logs=>[], :cli=>[], :chef=>[], :other=>[], :bc_import=>[] }
    Dir.entries(export_dir).each do |f|
      if f =~ /^\./
        next # ignore rest of loop
      elsif f =~ /^KEEP_THIS.*/
        next # ignore rest of loop
      elsif f =~ /^crowbar-logs-.*/
        @exports[:logs] << f 
      elsif f =~ /^crowbar-cli-.*/
        @exports[:cli] << f
      elsif f =~ /^crowbar-chef-.*/
        @exports[:chef] << f 
      elsif f =~ /(.*).import.log$/
        @exports[:bc_import] << f 
      else
        @exports[:other] << f
      end
      @exports[:count] += 1
      @file = params['file'] if params['file']
      @waiting = false if @file == f
    end
    respond_to do |format|
      format.html # index.html.haml
      format.json { render :json => @exports }
    end
  end

  def bootstrap
    if request.post?
      # only create if no other netwroks
      if BarclampNetwork::Network.count == 0
        deployment = Deployment.system_root.first
        BarclampNetwork::Network.transaction do
          net = BarclampNetwork::Network.create :name=>'admin', :description=>I18n.t('support.bootstrap.admin_net'),  :deployment_id=>deployment.id, :conduit=>'1g0', :v6prefix => "auto"
          BarclampNetwork::Range.create :name=>'admin', :network_id=>net.id, :first=>"192.168.124.10/24", :last=>"192.168.124.11/24"
          BarclampNetwork::Range.create :name=>'dhcp', :network_id=>net.id, :first=>"192.168.124.21/24", :last=>"192.168.124.80/24"
          BarclampNetwork::Range.create :name=>'host', :network_id=>net.id, :first=>"192.168.124.81/24", :last=>"192.168.124.254/24"
        end
      end
    end
    @roles = []
    @roles << Role.find_key("dns-server")
    @roles << Role.find_key("ntp-server")
    @roles << Role.find_key("network-server")
    @roles << Role.find_key("chef-server")
    @roles << Role.find_key("network-admin") || :create_network_admin
  end

  def restart
    @init = false
    if params[:id].nil?
      render
    elsif params[:id].eql? "request" or params[:id].eql? "import"
      @init = true
      render
    elsif params[:id].eql? "in_process"
      %x[sudo bluepill crowbar-webserver restart] unless Rails.env == 'development'
      render :json=>false
    elsif params[:id].eql? SERVER_PID
      render :json=>false
    elsif !params[:id].eql? SERVER_PID
      render :json=>true
    else
      render
    end
  end
  
  private 
  
  def ctime
    Time.now.strftime("%Y%m%d-%H%M%S")
  end
  
  def import_dir
    check_dir 'import'
  end
  
  def export_dir
    check_dir 'export'
  end

  def check_dir(type)
    d = File.join 'public', type
    unless File.directory? d
      Dir.mkdir d
    end
    return d    
  end
  
  def remove_file(type, name)
    begin
      f = File.join(check_dir(type), name)
      File.delete f
      flash[:notice] = t('support.index.delete_succeeded') + ": " + f
    rescue
      flash[:notice] = t('support.index.delete_failed') + ": " + f
    end
  end
  
  def extract_crowbar_yml(import_dir, tar, regen = true)
    archive = File.join import_dir,tar
    name = tar[/^(.*).tar.gz$/,1]
    name = tar[/^(.*).tgz$/,1] if name.nil?   #alternate ending
    name += '.yml'
    # extra from tar if not present
    if regen or !File.exist?(File.join(import_dir, name))
      crowbar = %x[tar -t -f #{archive} | grep crowbar.yml].strip
      %x[tar -x #{crowbar} -f #{archive} -O > #{File.join(import_dir, name)}] if crowbar
    end
    return name
  end
  
  def do_auth!
    case
    when request.fullpath.index("/get_cli") || request.full_path.index("/logs") then digest_auth!
    else
      super
    end
  end
end 

rails/app/views/support/bootstrap.html.haml
%h1= t '.title'

.column_40

  %h2
    = t '.roles'

  %ol
    - @roles.each do |r|
      - if r.nil?
        %li
          - rnew = 'network-admin'
          - jigname = Role.find_key('network-server').jig_name
          %a.button#bootstrap_bootstrap{:remote=>true}
            = t('.add', :role=>rnew)
      - else
        %li
          %a.role{:href => role_path(r.id, :form=>'true'), :title=>r.description, :id => r.id}= r.name

  %h2= t '.admin_server'

  - if Node.count == 0 
    - name = %x{hostname -f}.strip
    - if name =~ Node::FQDN_RE
      %a.button#bootstrap_adminserver{:remote=>true}
        = t '.create', :server=>name
    - else
      = t '.not_fqdn', :server=>name
  -else
    - Node.admin.each do |n|
      =link_to n.name, node_path(n.id)

  %h2= t '.monitor'
  = link_to t('.anneal'), annealer_path()

.column_50
  %p
  %section.box#role_edit
    = t '.hint'

:javascript

  $(document).ready(function() {  
    
    $.loadDetails('role', 'role_edit');

    $("a#bootstrap_bootstrap").on("click", function() {
      $.post("#{bootstrap_path()}");
      location.reload();
    });

    $("a#bootstrap_adminserver").on("click", function() {
      $.post("#{make_admin_path(:version=>'v2')}");
      location.reload();
    });

  });

rails/app/views/support/import.html.haml
- o = %x[cat /etc/*release]
- if o =~ /DESCRIPTION/
  - crowbar_os = o[/DISTRIB_DESCRIPTION="(.*)"/,1]
- else
  - crowbar_os = o.split("\n")[0]

%h1= t '.title_all'

.column_100
  %section.box#details
    %strong= t('.admin_os') + ": " + crowbar_os
    %div

%table.data.box
  %thead
    %tr
      %th= t '.name'
      %th= t '.order'
      %th= t '.user'
      %th= t '.version'
  %tbody
    - @barclamps.each do |bc|
      %tr{:id=>bc.id, :class => ["barclamp", cycle(:odd, :even, :name => "barclamps")]}
        %td{:title=>(bc.description || t('not_set'))}
          %em= bc.name
        %td= bc.order
        %td= t (bc.user_managed ? 'yes' : 'no')
        %td{:title=>t('.commit')+': '+(bc.commit || t('unknown'))}= (bc.build_on || t('unknown')).split('-')[0]

rails/app/views/support/index.html.haml
%p{:style => 'float:right'}
  - Barclamp.all.each do |bc|
    - c = "Barclamp#{bc.name.camelize}::#{bc.name.camelize}Controller"
    - if (eval(c).new.methods.include?('export') rescue false)
      = link_to t("export.#{bc.name}_export"), utils_export_path(:controller=>bc.name), :class => 'button'
    - ec = "Barclamp#{bc.name.camelize}::BarclampsController"
    - if (eval(ec).new.methods.include?('export') rescue false)
      = link_to t("export.#{bc.name}_export"), eval("barclamp_#{bc.name}.export_barclamps_path"), :class => 'button'

%h1= t '.title'
-if @waiting
  %em= t '.wait'
  
-if @exports[:count] == 0
  %h3= t '.none_exported'
-else
  - @exports.each do |key, value|
    - if key != :count
      -if value.length != 0
        %h3=t ".#{key}", :default=>key.to_s.titlecase
        %ul        
          -value.sort.reverse.each do |file|
            %li
              -if @file==file
                %em#new= t('new')
              %a{:href=>"/export/#{file}"}
                = file
              = link_to image_tag('/images/icons/delete.png'), utils_files_path(:id => file), :title=>t('.delete_hint')
            
.clear

:javascript
  
  function update() {
    $.ajaxSetup({ timeout: #{ (@waiting ? 1000 : 10000) }})
    $.getJSON('utils?format=json', function(data) {     
      if (data['count'] != #{@exports[:count]})
        location.href = '#{utils_path}?file=#{Haml::Helpers.html_escape params["file"]}';
    });      
  }

  $('#new').hide(5000);
  

rails/app/views/support/restart.html.haml
%h1= t '.title'

- if @init
  %table
    %tr
      %td
        .led{:class => 'off'}
      %td#status
        = "#{t '.in_process'}"

  - log = File.join RAILS_ROOT, 'public', 'export', SERVER_PID+'.import.log'
  - if params[:id].eql? "import" and File.exist?(log)
    %br
    .column_100
      %section.box#details
        %h3
          = t('.import_log')
          = ':'
          = link_to SERVER_PID+'.import.log', utils_files_path
        %div
          - File.open(log, 'r').each do |line|
            %p= line
            
- else
  = link_to t('.button'), restart_path(:id=>'request'), :class => 'button', :id=>'restart_button'
  
.clear

:javascript
  
  function update() {
    if (#{@init}) {
      jUrl = '/utils/restart/#{SERVER_PID}?format=json';
      $.get('/utils/restart/in_process');
      $.ajaxSetup({ timeout: 100});
      $.ajax({url: jUrl, success: function(data) {   
        if (data) {
          $('.led').attr('class','led ready');
          $('#status').text('#{t(".complete")}');
          location.href = "/utils/import";
          }
        else {
          $('.led').attr('class','led pending');
          $('#status').text('#{Rails.env=="development" ? t(".dev_restart") : t(".restarting")}');
        }
      }, error: function(XMLHttpRequest, textStatus, errorThrown){
        $('.led').attr('class','led in_process');
        $('#status').text('#{t(".server_down")}');
      }});      
    }
  }