rails/config/routes.rb
# Copyright 2013, Dell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
Crowbar::Application.routes.draw do

  # UI scope

  # special case items that allow IDs to have .s 
  constraints(:id => /.*/ ) do
    resources :nodes do
      resources :node_roles
      resources :attribs
    end
  end

  # UI resources (should generally match the API paths)
  get "annealer", :to => "node_roles#anneal", :as => :annealer
  resources :attribs
  resources :barclamps
  resources :deployments do
    get :head
    get :next
    resources :roles
  end
  resources :deployment_roles
  get 'docs', to: 'docs#index'
  get 'docs/:id', to: 'docs#show', constraints: {id: /[^\?]*/}
#  resources :docs
  resources :groups
  resources :jigs
  resources :node_roles  do
    put :retry
  end
  resources :roles
  resources :snapshots do
    resources :node_roles
    get :graph
    put :propose
    put :commit
    put :recall
  end

  namespace :barclamp_network do
    resources :interfaces
    resources :networks do
      get :ranges
      get :routers
      get :allocations
    end
    # special views
    get 'map' => "networks#map", :as=> :network_map
  end

  # UI only functionality to help w/ visualization
  scope 'dashboard' do
    get 'list(/:deployment)'  => 'dashboard#list', :as => :bulk_edit
    put 'list'                => 'dashboard#list', :as => :bulk_edit
    get 'layercake'           => 'dashboard#layercake', :as => :layercake
  end
  
  # UI only functionality to help w/ visualization
  scope 'utils' do
    get '/'             => 'support#index', :as => :utils
    get 'i18n/:id'      => 'support#i18n', :as => :utils_i18n, :constraints => { :id => /.*/ }
    get 'marker/:id'    => 'support#marker', :as => :utils_marker
    get 'files/:id'     => 'support#index', :as => :utils_files
    get 'import(/:id)'  => 'support#import', :as => :utils_import
    get 'upload/:id'    => 'support#upload', :as => :utils_upload
    get 'restart/:id'   => 'support#restart', :as => :restart
    get 'digest'        => "support#digest"
    get 'fail'          => "support#fail"
    match "bootstrap"     => "support#bootstrap", :as => :bootstrap
    namespace :scaffolds do
      resources :attribs do as_routes end
      resources :barclamps do as_routes end
      resources :docs do as_routes end
      resources :deployments do as_routes end
      resources :groups do as_routes end
      resources :jigs do as_routes end
      resources :navs do as_routes end
      resources :nodes do as_routes end
      resources :roles do as_routes end
      resources :role_requires do as_routes end
      resources :runs do as_routes end
      resources :snapshots do as_routes end
      resources :node_roles do as_routes end
      resources :deployment_roles do as_routes end
      resources :networks do as_routes end
      resources :routers do as_routes end
      resources :ranges do as_routes end
      resources :allocations do as_routes end
    end
  end

  # UI scope - legacy methods
  scope 'support' do
    get 'logs', :controller => 'support', :action => 'logs'
    get 'get_cli', :controller => 'support', :action => 'get_cli'
  end

  # these are ok, but really should move to the user resource!
  put 'reset_password(/:id)', :controller => 'users', :action=>"reset_password", :as=>:reset_password
  get 'edit_password/:id', :controller => 'users', :action=>'edit_password', :constraints => { :id => /.*/ }, :as => :edit_password
  delete 'unlock/:id', :controller => 'users', :action=>'unlock', :constraints => { :id => /.*/ }, :as => :unlock
  post 'lock/:id', :controller => 'users', :action=>'lock', :constraints => { :id => /.*/ }, :as => :lock
  match "manage_users", :controller => 'users', :action => 'index'
  match "delete_users", :controller => 'users', :action => 'delete_users', :as=> :delete_users

  devise_for :users, { :path_prefix => 'my', :module => :devise, :class_name=> 'Crowbar::User' }

  get    "/users/new(.:format)", :controller => 'users', :action=>'index', :as=> :new_user
  resources :users, :except => :new

  # API routes (must be json and must prefix v2)()
  scope :defaults => {:format => 'json'} do

    constraints(:id => /([a-zA-Z0-9\-\.\_]*)/, :version => /v[1-9]/) do

      # framework resources pattern (not barclamps specific)
      scope 'api' do
        scope 'status' do
          get "nodes(/:id)" => "nodes#status", :as => :nodes_status
          get "snapshots(/:id)" => "snapshots#status", :as => :snapshots_status
        end
        scope 'test' do
          put "nodes(/:id)" => "nodes#test_load_data"
        end
        scope ':version' do
          # These are not restful.  They poke the annealer and wait if you pass "sync=true".
          get "anneal", :to => "node_roles#anneal", :as => :anneal
          post "make_admin", :to => "nodes#make_admin", :as => :make_admin
          resources :attribs
          resources :barclamps
          resources :deployments do
            get :head
            get :next
            resources :roles
            resources :nodes
            put 'claim/:node_id' => "deployments#claim"
          end
          resources :deployment_roles do
            resources :attribs
          end
          resources :groups do
            member do
              get 'nodes'
            end
          end
          namespace :barclamp_network do
            resources :networks do
              resources :ranges
              resources :routers
              member do
                match 'ip'
                post 'allocate_ip'
                get 'allocations'
              end
            end
          end
          resources :interfaces
          resources :runs
          resources :jigs
          resources :nodes do
            resources :node_roles
            resources :attribs
            resources :roles
            put :reboot
            put :debug
            put :undebug
          end
          resources :node_roles do
            put :retry
          end
          resources :roles do
            resources :deployment_roles
            put 'template/:key/:value' => "roles#template"
          end
          resources :snapshots do
            resources :node_roles
            resources :nodes
            resources :roles
            resources :deployment_roles
            get :graph
            put :propose
            put :commit
            put :recall
          end
          resources :users do
            post "admin", :controller => "users", :action => "make_admin"
            delete "admin", :controller => "users", :action => "remove_admin"
            post "lock", :controller => "users", :action => "lock"
            delete "lock", :controller => "users", :action => "unlock"
            put "reset_password", :controller => "users", :action => "reset_password"
          end
        end # version
      end # api
    end # id constraints
  end # json

  # Install route from each root barclamp (should be done last so CB gets priority)
  begin
    Barclamp.roots.each do |bc|
      eval(IO.read(File.path(bc.source_path, "rails", "config", "routes.rb")), binding) unless bc.name.eql? 'crowbar'
    end
  rescue
    # startup cannot resolve Barclamp
  end

  root :to => 'dashboard#layercake'
end

rails/app/models/snapshot.rb
# Copyright 2013, Dell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

class Snapshot < ActiveRecord::Base

  ARCHIVED = -1
  PROPOSED = 0
  COMMITTED = 1
  ACTIVE = 2
  ERROR = 3
  STATES = {
    ARCHIVED => "archived",
    PROPOSED => "proposed",
    COMMITTED => "committed",
    ACTIVE => "active",
    ERROR => "error"
  }
  
  attr_accessible :id, :name, :description, :order, :deployment_id, :snapshot_id
  
  belongs_to      :deployment

  has_many        :deployment_roles,  :dependent => :destroy
  has_many        :roles,             :through => :deployment_roles

  has_many        :node_roles,        :dependent => :destroy
  has_many        :nodes,             :through => :node_roles
 
  has_one         :snapshot
  alias_attribute :next,              :snapshot

  def self.state_name(s)
    raise("#{state || 'nil'} is not a valid Snapshot state!") unless s and STATES.include? s
    I18n.t(STATES[s], :scope=>'node_role.state')
  end

  def state_name(s)
    self.class.state_name(s)
  end

  def active?
    committed? &&
      node_roles.committed.not_in_state(NodeRole::ACTIVE).count == 0
  end

  def committed?
    read_attribute('state') == COMMITTED
  end
  
  def proposed?
    read_attribute('state') == PROPOSED
  end

  def archived?
    read_attribute('state') == ARCHIVED
  end

  def annealable?
    committed? && !active? && !error?
  end

  def proposable?
    active? && !deployment.system?
  end

  def error?
    committed? &&
      node_roles.committed.in_state(NodeRole::ERROR).count > 0
  end

  def archive
    write_attribute("state",ARCHIVED)
    save!
  end

  def state
    s = read_attribute("state")
    
    return s if s == ARCHIVED || s == PROPOSED
    return ACTIVE if active?
    return ERROR if error?
    COMMITTED
  end

  def tail?
    snapshot_id.nil?
  end

  def parent
    Snapshot.where(:snapshot_id => id).first
  end

  class MissingJig < Exception
    def initalize(nr)
      @errstr = "NodeRole #{nr.name}: Missing jig #{nr.jig_name}"
    end

    def to_s
      @errstr
    end
    def to_str
      to_s
    end
  end

  # returns a hash with all the snapshot error status information 
  def status
    node_roles.each { |nr| s[nr.id] = nr.status if nr.error?  }
  end
  
    # commit the current proposal (cannot be done if there is a committed proposal)
  def commit
    raise I18n.t('deployment.commit.raise', :default=>'blocked: already 1 committed') unless proposed?
    NodeRole.transaction do
      node_roles.in_state(NodeRole::PROPOSED).each { |nr| nr.commit! }
    end
    parent.archive unless parent.nil?
    write_attribute("state",COMMITTED)
    save!
    Run.run!
    self
  end
  
  # create a new proposal from the this one
  def propose(name=nil)
    raise "Snapshot #{name} not ACTIVE, cannot create a new snapshot from it!" unless active?
    raise "Cannot propose a new snapshot for the system deployment!" if deployment.system?
    proposal = nil
    Deployment.transaction do
      # create the new proposal
      proposal = deep_clone(name)
      # move the pointer 
      deployment.snapshot_id = proposal.id
      archive
      deployment.save!
    end
    proposal
  end

  def recallable?
    !deployment.system?
  end
  
  # attempt to stop a proposal that's in transistion.
  # Do this by changing its state from COMMITTED to PROPOSED.
  def recall
    raise "Cannot recall a system deployment" unless recallable?
    write_attribute("state",PROPOSED)
    save!
  end

  ##
  # Clone this snapshot.  It will also clone any node roles specific to this snapshot,
  # and take care of making sure that the node role dependency graph stays sane.
  def deep_clone(name=nil)
    Snapshot.transaction do
      newsnap = self.dup
      # build the linked list
      newsnap.snapshot_id = self.id
      newsnap.order += 1
      newsnap.name = name unless name.nil?
      newsnap.send(:write_attribute,"state",PROPOSED)
      newsnap.save!
      # collect the deployment roles
      self.deployment_roles.each do |dr|
        new_dr = dr.dup
        new_dr.snapshot = newsnap
        new_dr.save!
        newsnap.deployment_roles << new_dr
      end
      # collect the node roles
      node_role_map = Hash.new
      self.node_roles.each do |nr| 
        Rails.logger.info("Snapshot: duplicating NodeRole #{nr.id}")
        new_nr = nr.dup
        new_nr.snapshot = newsnap
        # store the new nr because we need it for relationships (it's automatically linked to the snapshot when created)
        node_role_map[nr.id] = [nr,new_nr]
      end
      node_role_map.each do |id,nr_array|
        old_nr = nr_array[0]
        new_nr = nr_array[1]
        old_nr.children.each do |c_nr|
          new_nr.children << (node_role_map[c_nr.id][1] || c_nr rescue c_nr)
        end
        old_nr.parents.each do |p_nr|
          new_nr.parents << (node_role_map[p_nr.id][1] || p_nr rescue p_nr)
        end
        new_nr.save!
      end
      newsnap.save!
      newsnap
    end
  end
end

rails/app/controllers/scaffolds/snapshots_controller.rb
# Copyright 2013, Dell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

class Scaffolds::SnapshotsController < ApplicationController
  active_scaffold :snapshot do |conf|
  end
end 

rails/app/controllers/snapshots_controller.rb
# Copyright 2013, Dell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
class SnapshotsController < ApplicationController

  def index
    @list = Snapshot.order("id DESC").all
    respond_to do |format|
      format.html { }
      format.json { render api_index :snapshot, @list }
    end
  end

  def show
    respond_to do |format|
      format.html {
        @snapshot = Snapshot.find_key params[:id]
        @roles = @snapshot.deployment_roles.sort{|a,b|a.role.cohort <=> b.role.cohort}
        # alpha lists by ID
        @nodes = Node.order("name ASC").select do |n|
          (n.deployment_id == @snapshot.deployment_id) ||
          (n.node_roles.where(:snapshot_id => @snapshot.id).count > 0)
        end
      }
      format.json { render api_show :snapshot, Snapshot }
    end
  end

  def create
    unless Rails.env.development?
      render  api_not_supported("post", "snapshot")
    else
      r = Snapshot.create! params
      render api_show :snapshot, Snapshot, nil, nil, r
    end
  end

  def update
    unless Rails.env.development?
      render  api_not_supported("delete", "snapshot")
    else
      render api_update :snapshot, Snapshot
    end
  end

  def destroy
    unless Rails.env.development?
      render  api_not_supported("delete", "snapshot")
    else
      render api_delete Snapshot
    end
  end

  def anneal
    @snapshot = Snapshot.find_key params[:snapshot_id]
    @list = NodeRole.peers_by_state(@snapshot, NodeRole::TRANSITION).order("cohort,id")
    respond_to do |format|
      format.html {  }
      format.json { render api_index :node_roles, @list }
    end
  end

  def graph
    @snapshot = Snapshot.find_key params[:snapshot_id]
    respond_to do |format|
      format.html {  }
      format.json { 
        graph = []
        @snapshot.node_roles.each do |nr|
          vertex = { "id"=> nr.id, "name"=> "#{nr.node.alias}: #{nr.role.name}", "data"=> {"$color"=>"#83548B"}, "$type"=>"square", "$dim"=>15, "adjacencies" =>[] }
          nr.children.each do |c|
            vertex["adjacencies"] << { "nodeTo"=> c.id, "nodeFrom"=> nr.id, "data"=> { "$color" => "#557EAA" } }
          end
          graph << vertex
        end
        render :json=>graph.to_json, :content_type=>cb_content_type(:list) 
      }
    end    
  end

  def propose
    snap = Snapshot.find_key params[:snapshot_id]
    new_snap = snap.propose params[:name]
    respond_to do |format|
      format.html { redirect_to snapshot_path(new_snap.id) }
      format.json { render api_show :snapshot, Snapshot, nil, nil, new_snap }
    end
  end

  def commit 
    snap = Snapshot.find_key params[:snapshot_id]
    snap.commit
    respond_to do |format|
      format.html { redirect_to snapshot_path(snap.id) }
      format.json { render api_show :snapshot, Snapshot, nil, nil, snap }
    end
  end

  def recall
    snap = Snapshot.find_key params[:snapshot_id]
    snap.recall
    respond_to do |format|
      format.html { redirect_to snapshot_path(snap.id) }
      format.json { render api_show :snapshot, Snapshot, nil, nil, snap }
    end      
  end

end

rails/app/views/snapshots/_index.html.haml
- if list.length == 0
  = t 'no_items'
- else
  %table.data.box
    %thead
      %tr
        %th= t '.state'
        %th= t '.deployment'
        %th= t '.state'
        %th= t '.snapshot'
        %th= t '.description'
    %tbody
      - list.each do |i|
        - state = i.state 
        %tr
          %td
            .led{:class => Snapshot::STATES[state], :title=>Snapshot.state_name(state)}
          %td= link_to i.deployment.name, deployment_path(i.deployment.id)
          %td= Snapshot.state_name(state)
          %td= link_to i.name, snapshot_path(:id=>i.id) 
          %td= i.description

rails/app/views/snapshots/anneal.html.haml
- state = @snapshot.state
- if @snapshot and state == NodeRole::TODO
  %p{:style => 'float:right'}
    = link_to t('.anneal'), annealer_path(), :class => 'button', :"data-method"=>:put
%table.plane
  %tr
    %td
      .led{:class => NodeRole::STATES[state || NodeRole::ERROR], :title=>NodeRole.state_name(state)}
    %td
      %h1
        = link_to @snapshot.name, snapshot_path(@snapshot.id) if @snapshot
        = t '.title'

= render :partial=>'node_roles/index', :locals => { :list => @list }

%h2= t '.todo'
- todo = NodeRole.peers_by_state(@snapshot, NodeRole::TODO)
= render :partial=>'node_roles/index', :locals => { :list => todo }

%h2= t '.blocked'
- blocked = NodeRole.peers_by_state(@snapshot, NodeRole::BLOCKED)
= render :partial=>'node_roles/index', :locals => { :list => blocked }

.clear

:javascript

  function update() {
    $.ajaxSetup({ timeout: 1000 });
    location.reload();
  }

rails/app/views/snapshots/graph.html.haml
= javascript_include_tag 'infovis/jit'
= javascript_include_tag 'infovis/jit-yc'  #this may not be needed, please review

%h1= t '.title', :snapshot=>@snapshot.name

%div#infovis
  %div#infovis-canvaswidget
    %canvas#infovis-canvas

%div.tip#_tooltip{:style=>"position: absolute; z-index: 13000; top: 5%; left: 5%; width: 0px auto; height: 30%; display: none;"}

.clear

:javascript

$(document).ready(function() {

  var labelType = 'HTML';
  var useGradients = true; 
  var nativeTextSupport = false;
  var animate = true;

    // init ForceDirected
    var fd = new $jit.ForceDirected({
      //id of the visualization container
      injectInto: 'infovis',
      //Enable zooming and panning
      //by scrolling and DnD
      Navigation: {
        enable: true,
        //Enable panning events only if we're dragging the empty
        //canvas (and not a node).
        panning: 'avoid nodes',
        zooming: 10 //zoom speed. higher is more sensible
      },
      // Change node and edge styles such as
      // color and width.
      // These properties are also set per node
      // with dollar prefixed data-properties in the
      // JSON structure.
      Node: {
        overridable: true
      },
      Edge: {
        overridable: true,
        color: '#23A4FF',
        lineWidth: 0.4
      },
      //Native canvas text styling
      Label: {
        type: labelType, //Native or HTML
        size: 10,
        style: 'bold'
      },
      //Add Tips
      Tips: {
        enable: true,
        onShow: function(tip, node) {
          //count connections
          var count = 0;
          node.eachAdjacency(function() { count++; });
          //display node info in tooltip
          tip.innerHTML = "<div class=\"tip-title\">" + node.name + "</div>"
            + "<div class=\"tip-text\"><b>connections:</b> " + count + "</div>";
        }
      },
      // Add node events
      Events: {
        enable: true,
        type: 'Native',
        //Change cursor style when hovering a node
        onMouseEnter: function() {
          fd.canvas.getElement().style.cursor = 'move';
        },
        onMouseLeave: function() {
          fd.canvas.getElement().style.cursor = '';
        },
        //Update node positions when dragged
        onDragMove: function(node, eventInfo, e) {
            var pos = eventInfo.getPos();
            node.pos.setc(pos.x, pos.y);
            fd.plot();
        },
        //Implement the same handler for touchscreens
        onTouchMove: function(node, eventInfo, e) {
          $jit.util.event.stop(e); //stop default touchmove event
          this.onDragMove(node, eventInfo, e);
        },
        //Add also a click handler to nodes
        onClick: function(node) {
          if(!node) return;
          // put stuff here
        }
      },
      //Number of iterations for the FD algorithm
      iterations: 200,
      //Edge length
      levelDistance: 130,
      // Add text to the labels. This method is only triggered
      // on label creation and only for DOM labels (not native canvas ones).
      onCreateLabel: function(domElement, node){
        domElement.innerHTML = node.name;
        var style = domElement.style;
        style.fontSize = "0.8em";
        style.color = "#ddd";
      },
      // Change node styles when DOM labels are placed
      // or moved.
      onPlaceLabel: function(domElement, node){
        var style = domElement.style;
        var left = parseInt(style.left);
        var top = parseInt(style.top);
        var w = domElement.offsetWidth;
        style.left = (left - w / 2) + 'px';
        style.top = (top + 10) + 'px';
        style.display = '';
      }
    });

    // load JSON data.
    var json = null;     
    $.ajax( 
    { 
        async: false, 
        global: false, 
        url: "/api/v2/snapshots/#{@snapshot.id}/graph",
        dataType: 'json', 
        success: function(data) 
        { 
            json = data; 
        } 
    }); 

    console.debug(json);
    fd.loadJSON(json);

    // compute positions incrementally and animate.
    fd.computeIncremental({
      iter: 40,
      property: 'end',
      onStep: function(perc){
        console.debug(perc + '% loaded...');
      },
      onComplete: function(){
        console.debug('done');
        fd.animate({
          modes: ['linear'],
          transition: $jit.Trans.Elastic.easeOut,
          duration: 2500
        });
      }
    });
    // end

};

rails/app/views/snapshots/index.html.haml
%h1= t '.title'

= render :partial=>'index', :locals => { :list => @list }

rails/app/views/snapshots/show.html.haml
- state = @snapshot.state rescue Snapshot::ERROR
%table{:width=>'100%'}
  %tr
    %td
      .led{:class => Snapshot::STATES[state], :title=>Snapshot.state_name(state)}
    %td
      %h1
        = link_to @snapshot.deployment.name, deployment_path(@snapshot.deployment.id)
        = @snapshot.state_name(state)
    - if state == Snapshot::PROPOSED
      %td
        = form_for :deployment, :'data-remote' => true, :url => deployment_roles_path(:deployment_id=>@snapshot.deployment.id, :version=>'v2'), :html => { :method=>:post, :'data-type' => 'html',  :class => "formtastic" } do |f|
          - aroles = @snapshot.deployment.available_roles
          - if aroles.length > 0 
            = hidden_field_tag :snapshot_id, @snapshot.id
            = f.collection_select :role_id, aroles, :id, :name
            %input.button{:type => "submit", :name => "add", :value => t('.add_role')}
      %td= link_to t('.pick'), bulk_edit_path(), :title=>t('.pick_hint'), :class=>'button'
    - else
      %td= link_to t('.graph'), snapshot_graph_path(@snapshot.id), :class => 'button', :method=>:get
    %td= render :partial => 'deployments/buttons', :locals => { :state=>state, :snapshot=>@snapshot }

%table.snap{:align=>'left'}
  - if @nodes.count > 0 or  @roles.count > 0
    %thead
      %tr
        %th.anode= link_to t('.nodes'), bulk_edit_path()
        - @roles.each do |dr|
          %th.dr{:id=>dr.id}
            %div
              - name = (dr.role.name).truncate(30)
              = link_to name.gsub("-","&#8209;").html_safe, deployment_role_path(dr.id), :title=>dr.role.description
    %tbody
      - @nodes.each do |node|
        %tr.node{:id => node.id}
          %td.nodename
            = link_to node.alias, node_path(node.id), :title=>node.description
            - unless node.deployment_id == @snapshot.deployment.id
              = "("
              = link_to node.deployment.name, deployment_path(node.deployment_id), :title=>node.deployment.description
              = ")"
          - @roles.each do |dr|
            - nr = node.node_roles.where(:role_id => dr.role_id, :snapshot_id => dr.snapshot_id).first
            %td.noderole{:id=>(nr ? nr.id : -1), :dr=>dr.id}
              - if nr
                %span{:align=>'center'}
                  .led{:style=>"width:17px; margin:0px auto; text-align:center", :class => NodeRole::STATES[nr.state || NodeRole::ERROR], :title=>nr.role.name}
                    = link_to "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".html_safe, node_role_path(nr.id)
              - elsif state == Snapshot::PROPOSED
                %span{:style=>"margin-left:30%; display:none"}
                  = link_to image_tag('/images/icons/add.png'), node_roles_path(:snapshot_id=>@snapshot.id, :node_id=>node.id, :role_id=>dr.role.id), :method=>:post
  - else
    %tr
      %td= t 'no_items'

.clear

:javascript

  var height = 100;

  function update() {
    $.ajaxSetup({ timeout: 1000 });
    if (#{state != Snapshot::PROPOSED}) {
      location.reload();
    }
  };
  
  $('th.dr div a').each(function(){ 
    w = parseInt($(this).width());
    if (w > height) height = w;
  });

  $(document).ready(function() {

    $('th.dr').each(function(){
      $(this).height(height+5);
    });

    // set hover showing
    $('td.noderole')
      .bind('hover',
        function( ev ) {
          id = $(this).attr("id")
          dr = $(this).attr("dr");
          if (id == -1 && dr > 0) {
            if (ev['type']=="mouseenter")
              { $(this).children().show();  
                // $("td.dr#"+dr).css("font-weight","italic"); 
              }
            else if (ev['type']=="mouseleave")
              { $(this).children().hide(); 
                // $("td.dr#"+dr).css("font-weight","normal"); 
              }
          }
        }
      );
  });