rails/config/routes.rb
# Copyright 2013, Dell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
Crowbar::Application.routes.draw do

  # UI scope

  # special case items that allow IDs to have .s 
  constraints(:id => /.*/ ) do
    resources :nodes do
      resources :node_roles
      resources :attribs
    end
  end

  # UI resources (should generally match the API paths)
  get "annealer", :to => "node_roles#anneal", :as => :annealer
  resources :attribs
  resources :barclamps
  resources :deployments do
    get :head
    get :next
    resources :roles
  end
  resources :deployment_roles
  get 'docs', to: 'docs#index'
  get 'docs/:id', to: 'docs#show', constraints: {id: /[^\?]*/}
#  resources :docs
  resources :groups
  resources :jigs
  resources :node_roles  do
    put :retry
  end
  resources :roles
  resources :snapshots do
    resources :node_roles
    get :graph
    put :propose
    put :commit
    put :recall
  end

  namespace :barclamp_network do
    resources :interfaces
    resources :networks do
      get :ranges
      get :routers
      get :allocations
    end
    # special views
    get 'map' => "networks#map", :as=> :network_map
  end

  # UI only functionality to help w/ visualization
  scope 'dashboard' do
    get 'list(/:deployment)'  => 'dashboard#list', :as => :bulk_edit
    put 'list'                => 'dashboard#list', :as => :bulk_edit
    get 'layercake'           => 'dashboard#layercake', :as => :layercake
  end
  
  # UI only functionality to help w/ visualization
  scope 'utils' do
    get '/'             => 'support#index', :as => :utils
    get 'i18n/:id'      => 'support#i18n', :as => :utils_i18n, :constraints => { :id => /.*/ }
    get 'marker/:id'    => 'support#marker', :as => :utils_marker
    get 'files/:id'     => 'support#index', :as => :utils_files
    get 'import(/:id)'  => 'support#import', :as => :utils_import
    get 'upload/:id'    => 'support#upload', :as => :utils_upload
    get 'restart/:id'   => 'support#restart', :as => :restart
    get 'digest'        => "support#digest"
    get 'fail'          => "support#fail"
    match "bootstrap"     => "support#bootstrap", :as => :bootstrap
    namespace :scaffolds do
      resources :attribs do as_routes end
      resources :barclamps do as_routes end
      resources :docs do as_routes end
      resources :deployments do as_routes end
      resources :groups do as_routes end
      resources :jigs do as_routes end
      resources :navs do as_routes end
      resources :nodes do as_routes end
      resources :roles do as_routes end
      resources :role_requires do as_routes end
      resources :runs do as_routes end
      resources :snapshots do as_routes end
      resources :node_roles do as_routes end
      resources :deployment_roles do as_routes end
      resources :networks do as_routes end
      resources :routers do as_routes end
      resources :ranges do as_routes end
      resources :allocations do as_routes end
    end
  end

  # UI scope - legacy methods
  scope 'support' do
    get 'logs', :controller => 'support', :action => 'logs'
    get 'get_cli', :controller => 'support', :action => 'get_cli'
  end

  # these are ok, but really should move to the user resource!
  put 'reset_password(/:id)', :controller => 'users', :action=>"reset_password", :as=>:reset_password
  get 'edit_password/:id', :controller => 'users', :action=>'edit_password', :constraints => { :id => /.*/ }, :as => :edit_password
  delete 'unlock/:id', :controller => 'users', :action=>'unlock', :constraints => { :id => /.*/ }, :as => :unlock
  post 'lock/:id', :controller => 'users', :action=>'lock', :constraints => { :id => /.*/ }, :as => :lock
  match "manage_users", :controller => 'users', :action => 'index'
  match "delete_users", :controller => 'users', :action => 'delete_users', :as=> :delete_users

  devise_for :users, { :path_prefix => 'my', :module => :devise, :class_name=> 'Crowbar::User' }

  get    "/users/new(.:format)", :controller => 'users', :action=>'index', :as=> :new_user
  resources :users, :except => :new

  # API routes (must be json and must prefix v2)()
  scope :defaults => {:format => 'json'} do

    constraints(:id => /([a-zA-Z0-9\-\.\_]*)/, :version => /v[1-9]/) do

      # framework resources pattern (not barclamps specific)
      scope 'api' do
        scope 'status' do
          get "nodes(/:id)" => "nodes#status", :as => :nodes_status
          get "snapshots(/:id)" => "snapshots#status", :as => :snapshots_status
        end
        scope 'test' do
          put "nodes(/:id)" => "nodes#test_load_data"
        end
        scope ':version' do
          # These are not restful.  They poke the annealer and wait if you pass "sync=true".
          get "anneal", :to => "node_roles#anneal", :as => :anneal
          post "make_admin", :to => "nodes#make_admin", :as => :make_admin
          resources :attribs
          resources :barclamps
          resources :deployments do
            get :head
            get :next
            resources :roles
            resources :nodes
            put 'claim/:node_id' => "deployments#claim"
          end
          resources :deployment_roles do
            resources :attribs
          end
          resources :groups do
            member do
              get 'nodes'
            end
          end
          namespace :barclamp_network do
            resources :networks do
              resources :ranges
              resources :routers
              member do
                match 'ip'
                post 'allocate_ip'
                get 'allocations'
              end
            end
          end
          resources :interfaces
          resources :runs
          resources :jigs
          resources :nodes do
            resources :node_roles
            resources :attribs
            resources :roles
            put :reboot
            put :debug
            put :undebug
          end
          resources :node_roles do
            put :retry
          end
          resources :roles do
            resources :deployment_roles
            put 'template/:key/:value' => "roles#template"
          end
          resources :snapshots do
            resources :node_roles
            resources :nodes
            resources :roles
            resources :deployment_roles
            get :graph
            put :propose
            put :commit
            put :recall
          end
          resources :users do
            post "admin", :controller => "users", :action => "make_admin"
            delete "admin", :controller => "users", :action => "remove_admin"
            post "lock", :controller => "users", :action => "lock"
            delete "lock", :controller => "users", :action => "unlock"
            put "reset_password", :controller => "users", :action => "reset_password"
          end
        end # version
      end # api
    end # id constraints
  end # json

  # Install route from each root barclamp (should be done last so CB gets priority)
  begin
    Barclamp.roots.each do |bc|
      eval(IO.read(File.path(bc.source_path, "rails", "config", "routes.rb")), binding) unless bc.name.eql? 'crowbar'
    end
  rescue
    # startup cannot resolve Barclamp
  end

  root :to => 'dashboard#layercake'
end

rails/app/controllers/dashboard_controller.rb
# Copyright 2013, Dell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
class DashboardController < ApplicationController

  def layercake
    # we may want to move this into the database at some point
    taxmap = JSON::load File.open(File.join("config", "layercake.json"), 'r')
    @layers = {}
    @status = {}
    taxmap["layers"].each { |k| @layers[k]=[] }
    NodeRole.current.each do |nr|
      layer = taxmap[nr.role.name] || 'apps'
      @layers[layer] << nr 
      if nr.state == NodeRole::ERROR
        @status[layer] = 'error'
      elsif (nr.state == NodeRole::PROPOSED)
        @status[layer] = 'user'
      elsif nr.state != NodeRole::ACTIVE
        @status[layer] = 'system'
      end
    end

    respond_to do |format|
      format.html { }
    end
  end    

  def group_change
    # TODO: not used?
    node = Node.find_by_name params[:id]
    if node.nil?
      raise "Node #{params[:id]} not found.  Cannot change group" 
    else
      group = params[:group]
      if params.key? 'automatic'
        node.group=""
      else
        node.group=group
      end
      node.save
      Rails.logger.info "node #{node.name} (#{node.alias}) changed its group to be #{node.group.empty? ? 'automatic' : group}."
      render :inline => "SUCCESS: added #{node.name} to #{group}.", :cache => false 
    end
  end
  

  # Bulk Edit
  def list
    if request.put?
      nodes = {}
      params.each do |k, v|
        if k.starts_with? "node:"
          parts = k.split ':'
          node = parts[1]
          area = parts[2]
          nodes[node] ||= {} 
          nodes[node][area] = (v.empty? ? nil : v)
        end
      end
      succeeded = []
      failed = []
      nodes.each do |node_name, values|
        node = Node.find_key node_name
        begin
          node.update_attributes! values
          succeeded << node.alias
        rescue Exception=>e
          Rails.logger.info "user attempted dashboard.list put for node #{node.name} raised error #{e.message}"
          failed << node.alias
        end
      end
      if failed.length>0
        flash[:notice] = I18n.t('failed', :scope=>'dashboard.list', :list=>failed.join(','))
      elsif succeeded.length>0
        flash[:notice] = I18n.t('updated', :scope=>'dashboard.list', :list=>succeeded.join(','))
      end
    end
    @nodes = if params.key? :deployment
      @deployment = Deployment.find_key params[:deployment]
      @deployment.nodes
    else
      Node.all
    end
  end

  def families
    @families = {}
    Node.all.each do |n|
      f = n.family.to_s  
      @families[f] = {:names=>[], :family=>n.family} unless @families.has_key? f
      @families[f][:names] << {:alias=>n.alias, :description=>n.description, :handle=>n.name}
    end
  end

end

rails/app/views/dashboard/_layercake.html.haml
%div.layer= t ".#{layer}"
%div.dots
  - @layers[layer].each do |nr|
    - unless nr.nil?
      %span.led{:style=>"float:left", :class => NodeRole::STATES[nr.state || NodeRole::ERROR], 
                  :title=>"#{nr.node.alias} #{nr.role.name}"}
        = link_to "&nbsp;&nbsp;&nbsp;&nbsp;".html_safe, node_role_path(nr.id)

rails/app/views/dashboard/families.html.haml
%h1= t('.title')

%table.data.box
  %thead
    %tr
      %th= t('.name')
      %th= t('.units')
      %th= t('.ram')
      %th= t('.nics')
      %th= t('.drives')
      %th= t('.raid')
      %th= t('.hardware')
      %th= t('.cpu')
  %tbody
    - @families.each do |n, f|
      %tr{ :class => cycle(:odd, :even, :name => "family") }
        %td
          %ul.plain
            - f[:names].each do |node|
              %li= link_to node[:alias], node_path(node[:handle]), :title=> node[:description]
        %td= f[:names].length
        %td= format_memory(f[:family][:ram])
        %td= f[:family][:nics]
        %td= f[:family][:drives]
        %td= f[:family][:raid]
        %td= f[:family][:hw]
        %td= f[:family][:cpu]

rails/app/views/dashboard/index.html.haml
%p#add_button{:style => 'float:right'}
  = text_field_tag "new_group", t('.default_new'), :size => 15
  = link_to t('.add'), "javascript:add_group();", :class => 'button', :id=>'add_button'
%h1= t('.title')

.column_100
  - unless false
    %section.box#details
      - if params.include? :nopoll
        = t '.no_polling'
      - if @node
        = render :partial => 'show'
      - else
        %p= t(".status_empty") % Node.count
        %div{ :class=>'group', :draggable=>'true', :id=>Group.find_or_create_by_name_and_category('not_set', 'ui').id }
          =t('.drag_hint').html_safe

#nodes
  - if @groups.nil?
    = t 'no_items'
  - else
    - i = -1
    #add_group_div.column_25{:class => cb_column_class(1,4), :style=>'display:none' }
      %table.data.box{:id => "new_group_add"}
        %thead
          %tr
            %th.status
              %a{:href=>"javascript:hide_group();", :title=>t('.hide')}
                %img{:src=>"/images/icons/server_add.png"}
            %th{ :id=> 'new_group', :droptarget=>'true' }
              = "THIS TEXT GETS REPLACED"
        %tbody
          %tr
            %td 
            %td= t('.new_drag')
    - @groups.sort.each do |group|
      - next if group.name.eql? 'not_set' and group.nodes.count == 0
      .column_25{:class => cb_column_class(i+=1,4)}
        %table.data.box{:id => "group_#{group.id}"}
          %thead
            %tr
              - if group.nodes.count == 0
                %th.status{:title => t('.remove_group')}
                  %img{ :src=>'/images/icons/delete.png', :title=>t('.remove_group'), :onclick=>"javascript:remove_group(#{group.id});" }
              - else
                %th.status{:title => t('updating')}
                  .inline_piechart= [0, 0, 1, 0, 0]*','
              %th.group{:title=>group.description}
                - unless group[:automatic]
                  %div{ :class=>'group', :draggable=>'true', :id=>group.id }
                    = truncate(group.name, :length => 25)
                - else
                  %div{ :class=>'group', :draggable=>'true', :id=>'USE_AUTOMATIC!' }
                    %i= truncate(group.name, :length => 25)
  
          %tbody
            - group.nodes.each do |node|
              %tr{ :class => ["node", cycle(:odd, :even, :name => "nodes_#{i}")], :id => node.id }
                %td.status{:raw=> node.state }
                  .led{:class => node.status, :title=>t(node.status, :scope=>'status', :default=>node.status)} 
                %td.name
                  %a{:href => node_path(node.id), :draggable=>'true', :title=> (node.description.nil? ? t(:not_set) : node.description), :class => 'node_details', :id => node.id}
                    = truncate(node.alias, :length => 25)
  
.clear

:javascript
  groups = {};
  selected = '#{session[:node]}';
  
  function pie_title(total, ready, failed, unknown, unready, pending, building) {
    var status = "#{t :status_pie, :scope=>'dashboard.index'}";
    status = status.replace("{0}", total);
    status = status.replace("{1}", ready);
    status = status.replace("{2}", failed);
    status = status.replace("{3}", unknown);
    status = status.replace("{4}", unready+pending+building);
    return status;
  }
  
    // set draggable attributes
  $('a.node_details[draggable="true"]')
    .bind('dragend', function( ev ) {
      false;
    })
    .bind('dragstart', function( ev ) {
      // console.debug("dragging " + ev.target.id);
      var dt = ev.originalEvent.dataTransfer;
      // TODO make sure only a available set this!
      dt.setData("Text", ev.target.id);
    });

  // set droppable attributes using bind_drop
  $('div.group[draggable="true"]').each(function() { bind_drop($(this))} );

    
  function bind_drop(div) {
    // Decide whether the thing dragged in is welcome.
    div.bind('dragover', function(ev) {
        if (ev.preventDefault) ev.preventDefault(); // allows us to drop
        return false;
    });

    // Handle the final drop...
    div.bind('drop', function(ev) {
      if (ev.preventDefault) ev.preventDefault(); // allows us to drop
      var node = ev.originalEvent.dataTransfer.getData("Text");
      var group = $(this).attr('id');
      // console.debug(node + ' into ' + group );
      $.ajax({url:'/2.0/crowbar/2.0/group/'+group+'/node/'+node, dataType:'json', type:"PUT", 
        statusCode: { 200: function(data) { location.href = '#{dashboard_path}/'+selected; }}
      });
    });
  }
  
  function hide_group() {
    $('#add_group_div').attr('style','display:none');
  }
  
  function remove_group(id) {
    $.ajax({url:'/2.0/crowbar/2.0/group/'+id, type:"DELETE", dataType: 'json',
      statusCode: { 200: function(data) { $('#group_'+id).remove(); } }
    });
  }
  
  function add_group() {
    var group_div = $('#add_group_div');
    var new_group = $('#new_group').val();
    var group = $('th[droptarget="true"]');
    var valid_group_regex = /^[a-zA-Z][a-zA-Z0-9._-]+$/;
    if (new_group.match(valid_group_regex)) {
      // Create the group json and post it
      var group_data = {'name': new_group, 'description': new_group, 'category': 'ui'}
      $.ajax({url:"/2.0/crowbar/2.0/group", data:group_data, type:'POST', dataType:'json', 
        success:function(data) {
          // on success, add to the UI
          var id = data['id']
          group.attr('id', id);
          group.text(new_group);
          bind_drop($('#'+id.toString()));
          group_div.attr('style', 'display:inline');
          $('a#add_button').attr('class','button');}, 
        error:function(data) { 
          alert("#{t '.add_group_exists'}"); $('a#add_button').attr('class','button'); }
      })} 
    else {
      alert("#{t '.add_group_error'}");
      $('a#add_button').attr('class','button');
    }
  }
  
  function update() {
    // use nopoll parameter for debugging to prevent activity on web server
    // TODO: restore this:
    if (#{params.include?(:nopoll) ? 'false' : 'true'}) {
      $.ajaxSetup({ timeout: 3000 })
      $.getJSON('#{nodes_status_path()}', function(data) {
        
        // reload path
        var repath = '#{dashboard_path}/'+selected;
        
        // If node count has changed, re-render the page
        var current_nodes = $('.node').length;
        if(data['count'] != current_nodes) {
          location.href = repath;
        }
  
        // If node name sum has changed, re-render the page
        if(data['sum'] != #{@sum}) {
          location.href = repath;
        }
        
        // Update group-level piecharts
        $.each(data['groups'], function(key,val) {
          k = key.toString();
          var values = val['ready'] + ', ' + val['failed'] + ', ' + val['unknown'] + ', ' + (val['building']+val['unready']+val['pending']);
          var total = val['ready']+val['unready']+val['unknown']+val['building']+val['pending']+val['failed'];
          if (groups[k]==undefined) { 
            groups[k] = total; 
          } else if (groups[k]!=total) {
            location.href =repath;
          }
          $('#group_'+k+' th.status .inline_piechart').html(values).sparkline('html', piechart_options );
          $('#group_'+k+' th.status').attr('title', pie_title(total, val['ready'], val['failed'], val['unknown'], val['building'], val['unready'], val['pending']));
        });
        
        // Update nodes
        $.each(data['status'], function(key,val) {
          k = key.toString();
          var td = $('#'+k+' td.status');
          var led = td.children('.led');
          if(!(td.attr('raw') === val['raw'])) {
            led.destroy();
            led.attr('class', 'led '+val['status']);
            td.attr('raw', val['raw']);
            td.effect("highlight", {color: '#666666'}, 2000);
            led.attr('title', val['state']);
          }
          // catch the case where we've expanded detail on a node
          s = $('div.container dd.node_state');
          h_key = "head_"+k;
          h = $('div.container div.led[id="'+h_key+'"]');
          if (h.attr('id')==h_key && s.text()!=val['state']) {
            s.text(val['state']);
            s.effect("highlight", {color: '#666666'}, 2000);
            s.attr('title','#{t('raw')}: '+val['raw']);
            var head = $('#head_'+k);
            if (head.length !=0 ) {
              head.destroy();
              head.attr('class', 'led '+val['status']);
              head.attr('title', val['state']);
            }
          }
        });
      });
    }
  }

rails/app/views/dashboard/layercake.html.haml
#layercake

  %h1.title= t '.title'

  .column_25.first
    #core{:class=>(@status['core'] || 'ready')}
      = render :partial=>'layercake', :locals=>{ :layer=>'core' }
    #jigs{:class=>(@status['jigs'] || 'ready')}
      = render :partial=>'layercake', :locals=>{ :layer=>'jigs' }

  .column_75.last

    #apps{:class=>(@status['apps'] || 'ready')}
      = render :partial=>'layercake', :locals=>{ :layer=>'apps' }
    #services{:class=>(@status['services'] || 'ready')}
      = render :partial=>'layercake', :locals=>{ :layer=>'services' }
    #clients{:class=>(@status['clients'] || 'ready')}
      = render :partial=>'layercake', :locals=>{ :layer=>'clients' }
    #os{:class=>(@status['is'] || 'ready')}
      = render :partial=>'layercake', :locals=>{ :layer=>'os' }
    #nodes{:class=>(@status['nodes'] || 'ready')}
      = render :partial=>'layercake', :locals=>{ :layer=>'nodes' }
    #network{:class=>(@status['network'] || 'ready')}
      = render :partial=>'layercake', :locals=>{ :layer=>'network' }

.clear


:javascript

  function update() {
    $.ajaxSetup({ timeout: 1000 });
    location.reload();
  }

rails/app/views/dashboard/list.html.haml
%p{:style => 'float:right'}
  = select_tag "deployment", options_from_collection_for_select(Deployment.all, "name", "name", params[:deployment]), :id=>"filter"
%h1
  =t '.title'
  -if @deployment
    = link_to @deployment.name, deployment_path(@deployment.id), :title=>@deployment.description
  -else
    = t('all')

- # filter to only show unallocated nodes, with an option to display all
= form_for :dashboard, :'data-remote' => true, :url => '/dashboard/list', :html => { :method=>:put, :'data-type' => 'html',  :id => 'list', :class => "formtastic" } do |f|
  %table.data.box
    %thead
      %tr
        %th= t('.name')
        %th= t('.alias')
        %th= t('.description')
        %th= t('.deployment')
    %tbody
      - if @nodes and @nodes.count > 0
        - @nodes.sort_by{|n| n.alias }.each do |node|
          %tr.node{ :class => cycle(:odd, :even, :name => "nodes"), :id => node.id }
            %td= link_to node.name, node_path(node.id), :title=> node.addresses.join(',')
            %td= text_field_tag "node:#{node.id}:alias".to_sym, "#{node.alias}", :size => 15
            %td= text_field_tag "node:#{node.id}:description".to_sym, "#{node.description || ""}", :size => 30
            %td 
              - deployments = Deployment.all
              = select_tag "node:#{node.id}:deployment_id", options_from_collection_for_select(deployments, "id", "name", node.deployment.id)
      - else
        %tr
          %td{ :colspan=>4 }
            = t 'no_items'
    - if @nodes and @nodes.count > 0
      %tfoot
        %tr{ :class => cycle(:odd, :even, :name => "nodes")}
          %td.hint{:colspan => 3}
            = t 'note'
            %em= t '.hint'
          %td.action{:colspan => 1}
            %input.button{:type => "submit", :name => "submit", :value => t('save')}

.clear

  
:javascript

$(document).ready(function(){
  $("#filter").on("change", function() {
    url = $("#filter").find('option:selected').text();
    console.debug(url);
    window.location.href = "#{(@deployment.nil? ? "list/" : "")}"  +url;
  });
});