rails/config/routes.rb
# Copyright 2013, Dell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
Crowbar::Application.routes.draw do

  # UI scope

  # special case items that allow IDs to have .s 
  constraints(:id => /.*/ ) do
    resources :nodes do
      resources :node_roles
      resources :attribs
    end
  end

  # UI resources (should generally match the API paths)
  get "annealer", :to => "node_roles#anneal", :as => :annealer
  resources :attribs
  resources :barclamps
  resources :deployments do
    get :head
    get :next
    resources :roles
  end
  resources :deployment_roles
  get 'docs', to: 'docs#index'
  get 'docs/:id', to: 'docs#show', constraints: {id: /[^\?]*/}
#  resources :docs
  resources :groups
  resources :jigs
  resources :node_roles  do
    put :retry
  end
  resources :roles
  resources :snapshots do
    resources :node_roles
    get :graph
    put :propose
    put :commit
    put :recall
  end

  namespace :barclamp_network do
    resources :interfaces
    resources :networks do
      get :ranges
      get :routers
      get :allocations
    end
    # special views
    get 'map' => "networks#map", :as=> :network_map
  end

  # UI only functionality to help w/ visualization
  scope 'dashboard' do
    get 'list(/:deployment)'  => 'dashboard#list', :as => :bulk_edit
    put 'list'                => 'dashboard#list', :as => :bulk_edit
    get 'layercake'           => 'dashboard#layercake', :as => :layercake
  end
  
  # UI only functionality to help w/ visualization
  scope 'utils' do
    get '/'             => 'support#index', :as => :utils
    get 'i18n/:id'      => 'support#i18n', :as => :utils_i18n, :constraints => { :id => /.*/ }
    get 'marker/:id'    => 'support#marker', :as => :utils_marker
    get 'files/:id'     => 'support#index', :as => :utils_files
    get 'import(/:id)'  => 'support#import', :as => :utils_import
    get 'upload/:id'    => 'support#upload', :as => :utils_upload
    get 'restart/:id'   => 'support#restart', :as => :restart
    get 'digest'        => "support#digest"
    get 'fail'          => "support#fail"
    match "bootstrap"     => "support#bootstrap", :as => :bootstrap
    namespace :scaffolds do
      resources :attribs do as_routes end
      resources :barclamps do as_routes end
      resources :docs do as_routes end
      resources :deployments do as_routes end
      resources :groups do as_routes end
      resources :jigs do as_routes end
      resources :navs do as_routes end
      resources :nodes do as_routes end
      resources :roles do as_routes end
      resources :role_requires do as_routes end
      resources :runs do as_routes end
      resources :snapshots do as_routes end
      resources :node_roles do as_routes end
      resources :deployment_roles do as_routes end
      resources :networks do as_routes end
      resources :routers do as_routes end
      resources :ranges do as_routes end
      resources :allocations do as_routes end
    end
  end

  # UI scope - legacy methods
  scope 'support' do
    get 'logs', :controller => 'support', :action => 'logs'
    get 'get_cli', :controller => 'support', :action => 'get_cli'
  end

  # these are ok, but really should move to the user resource!
  put 'reset_password(/:id)', :controller => 'users', :action=>"reset_password", :as=>:reset_password
  get 'edit_password/:id', :controller => 'users', :action=>'edit_password', :constraints => { :id => /.*/ }, :as => :edit_password
  delete 'unlock/:id', :controller => 'users', :action=>'unlock', :constraints => { :id => /.*/ }, :as => :unlock
  post 'lock/:id', :controller => 'users', :action=>'lock', :constraints => { :id => /.*/ }, :as => :lock
  match "manage_users", :controller => 'users', :action => 'index'
  match "delete_users", :controller => 'users', :action => 'delete_users', :as=> :delete_users

  devise_for :users, { :path_prefix => 'my', :module => :devise, :class_name=> 'Crowbar::User' }

  get    "/users/new(.:format)", :controller => 'users', :action=>'index', :as=> :new_user
  resources :users, :except => :new

  # API routes (must be json and must prefix v2)()
  scope :defaults => {:format => 'json'} do

    constraints(:id => /([a-zA-Z0-9\-\.\_]*)/, :version => /v[1-9]/) do

      # framework resources pattern (not barclamps specific)
      scope 'api' do
        scope 'status' do
          get "nodes(/:id)" => "nodes#status", :as => :nodes_status
          get "snapshots(/:id)" => "snapshots#status", :as => :snapshots_status
        end
        scope 'test' do
          put "nodes(/:id)" => "nodes#test_load_data"
        end
        scope ':version' do
          # These are not restful.  They poke the annealer and wait if you pass "sync=true".
          get "anneal", :to => "node_roles#anneal", :as => :anneal
          post "make_admin", :to => "nodes#make_admin", :as => :make_admin
          resources :attribs
          resources :barclamps
          resources :deployments do
            get :head
            get :next
            resources :roles
            resources :nodes
            put 'claim/:node_id' => "deployments#claim"
          end
          resources :deployment_roles do
            resources :attribs
          end
          resources :groups do
            member do
              get 'nodes'
            end
          end
          namespace :barclamp_network do
            resources :networks do
              resources :ranges
              resources :routers
              member do
                match 'ip'
                post 'allocate_ip'
                get 'allocations'
              end
            end
          end
          resources :interfaces
          resources :runs
          resources :jigs
          resources :nodes do
            resources :node_roles
            resources :attribs
            resources :roles
            put :reboot
            put :debug
            put :undebug
          end
          resources :node_roles do
            put :retry
          end
          resources :roles do
            resources :deployment_roles
            put 'template/:key/:value' => "roles#template"
          end
          resources :snapshots do
            resources :node_roles
            resources :nodes
            resources :roles
            resources :deployment_roles
            get :graph
            put :propose
            put :commit
            put :recall
          end
          resources :users do
            post "admin", :controller => "users", :action => "make_admin"
            delete "admin", :controller => "users", :action => "remove_admin"
            post "lock", :controller => "users", :action => "lock"
            delete "lock", :controller => "users", :action => "unlock"
            put "reset_password", :controller => "users", :action => "reset_password"
          end
        end # version
      end # api
    end # id constraints
  end # json

  # Install route from each root barclamp (should be done last so CB gets priority)
  begin
    Barclamp.roots.each do |bc|
      eval(IO.read(File.path(bc.source_path, "rails", "config", "routes.rb")), binding) unless bc.name.eql? 'crowbar'
    end
  rescue
    # startup cannot resolve Barclamp
  end

  root :to => 'dashboard#layercake'
end

rails/app/models/deployment.rb
# Copyright 2013, Dell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

############
# 'snapshots' is the history relation. It contains all historical deployments.
# snapshot (or head) is the currently active proposal snapshot (or queued or committing)
#

class Deployment < ActiveRecord::Base
  
  after_create   :add_initial_snapshop
  before_create  :set_parent

  attr_accessible :name, :description, :parent_id

  validates_uniqueness_of   :name, :case_sensitive => false, :message => I18n.t("db.notunique", :default=>"Name item must be unique")
  validates_format_of       :name, :with=>/^[a-zA-Z][_a-zA-Z0-9]*$/, :message => I18n.t("db.lettersnumbers", :default=>"Name limited to [_a-zA-Z0-9]")
  
  has_many          :snapshots,           :dependent => :destroy
  has_one           :snapshot,            :class_name => "Snapshot", :primary_key => "snapshot_id", :foreign_key => 'id', :dependent => :destroy
  alias_attribute   :head,                :snapshot

  belongs_to        :parent,              :class_name => "Deployment"
  has_many          :nodes

  scope             :system_root,         -> { where(:system=>true) }   # cannot be named 'system' because of internal method name conflicts

  # active includes nothing being committed
  def active?
    head.active?
  end

  def committed?
    head.committed?
  end

  def proposed?
    head.proposed?
  end

  def state
    head.state
  end

  # Helper to atomically recommit a currently active or committed snapshot.
  def recommit(&block)
    raise "Can only be called on a system deployment" unless system?
    raise "Recommit must be passed a block that will take a snapshot!" unless block_given?
    Deployment.transaction do
      # if the head is committed (in transistion) then we can add it otherwise, we need to clone it
      new_c = (head.committed? ? head : head.deep_clone)
      block.call(new_c)
      new_c.save!
      # move the pointer (could be skipped if this was already head)
      self.snapshot_id = new_c.id 
      # reset all the node roles to ensure we re-evaluate
      new_c.node_roles.each { |nr| nr.commit! }
      self.save!
      return snapshot(true)
    end
  end

  # commit the current proposal (cannot be done if there is a committed proposal)
  def commit
    head.commit
  end
  
  # is this a system deployment?
  def system?
    read_attribute("system")
  end

  # available roles to be added to deployment
  def available_roles
    candidates = Role.active
    # except, don't include roles that we've already got
    in_use = head.roles
    candidates - in_use
  end

  # available nodes that could be used in the deployment
  def available_nodes
    self.nodes
  end

  # Lookup the roles available for the deployment, use the Proposal then Active 
  def roles
    head.roles
  end

  private

  def set_parent
    # 1st system deployment is a special case
    if Deployment.system_root.count == 0
      # Make it a system deployment write attribute because we don't allow direct access to system    
      self[:system]= true
    else
      # system is a safe fall back (unless we are system)
      self.parent_id ||= (Deployment.system_root.first.id rescue nil)
    end
  end

  # all deployments must have a snapshot
  def add_initial_snapshop
    s = Snapshot.create! :name=>self.name, :deployment_id=>self.id
    self.snapshot_id = s.id
    self.save!
  end

end

rails/app/controllers/deployments_controller.rb
# Copyright 2013, Dell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
class DeploymentsController < ApplicationController

  def index
    @list = Deployment.all
    respond_to do |format|
      format.html { }
      format.json { render api_index :deployment, @list }
    end
  end

  def show
    respond_to do |format|
      format.html { @deployment = Deployment.find_key params[:id] }
      format.json { render api_show :deployment, Deployment }
    end
  end

  def create
    @deployment = Deployment.create! params
    respond_to do |format|
      format.html { redirect_to deployment_path(@deployment.id)}
      format.json { render api_show :deployment, Deployment, @deployment.id.to_s, nil, @deployment }
    end
  end

  def destroy
    render api_delete Deployment
  end

  # return the committed snapshot
  def head
    deploy = Deployment.find_key params[:deployment_id]
    render_snaps(deploy.head)
  end

  # return the proposed snapshot
  def next
    deploy = Deployment.find_key params[:deployment_id]
    render_snaps(deploy.head.next)
  end

  def claim
    deploy = Deployment.find_key params[:deployment_id]
    node = Node.find_key params[:node_id]
    node.deployment_id = deploy.id
    node.save!
    node.reload
    render api_show :node, Node, nil, nil, node
  end

  private 

  def render_snaps(snap)
    respond_to do |format|
      format.html { redirect_to snapshot_path(snap.id) }
      format.json { render api_show :snapshot, Snapshot, nil, nil, snap }
    end
  end


end

rails/app/controllers/scaffolds/deployments_controller.rb
# Copyright 2013, Dell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

class Scaffolds::DeploymentsController < ApplicationController
  active_scaffold :deployment do |conf|
  end
end 

rails/app/views/deployments/_buttons.html.haml
- case
  - when snapshot.proposed?
    = link_to t('.commit'), snapshot_commit_path(snapshot.id, :version=>2), :class => 'button', :method=>:put
  - when snapshot.proposable?
    = form_for :snapshot, :'data-remote' => true, :url => snapshot_propose_path(:snapshot_id=>snapshot.id), :html => { :method=>:put, :'data-type' => 'html',  :class => "formtastic" } do |f|
      = text_field_tag :name, snapshot.name, :size => 15
      %input.button{:type => "submit", :name => "propose", :method=>:put, :value => t('.propose')}
  - when snapshot.annealable?
    = link_to t('.recall'), snapshot_recall_path(:snapshot_id=>snapshot.id), :class => 'button', :method=>:put
  - when snapshot.error?
    = link_to t('.correct'), snapshot_propose_path(:snapshot_id=>snapshot.id), :class => 'button', :method=>:put

rails/app/views/deployments/_new.html.haml
= form_for :deployment, :remote => false, :url => deployment_create_path(:barclamp_id=>barclamp.id), :html => { :'data-type' => 'html', :'data-method' => 'post', :method => :post, :id => 'create_deployment_form', :class => "formtastic"} do |f|
  %tr{:class => ["deployment", cycle(:odd, :even)]}
    %td
      = hidden_field_tag :barclamp, barclamp.id
      = text_field_tag :name, Barclamp::DEFAULT_DEPLOYMENT_NAME, :size => 15
    %td
      = text_field_tag :description, t('created_on', :date=>l(Time.now)), :size => 60
    %td
      %input.button{:type => "submit", :value => t('.propose')}

rails/app/views/deployments/_show.html.haml
%strong
  = link_to deployment.name, deployment_path(:barclamp_id=>deployment.barclamp.name, :id=>deployment.name)
  = ":"
  %em
    = deployment.description

rails/app/views/deployments/index.html.haml
%table{:width=>'100%'}
  %tr
    %td
      %h1= t '.title'
    %td{:align=>'right'}
      = form_for :deployment, :'data-remote' => true, :url => deployments_path(), :html => { :method=>:post, :'data-type' => 'html',  :class => "formtastic" } do |f|
        = text_field_tag :name, t('.default'), :size => 15
        %input.button{:type => "submit", :name => "create", :method=>:post, :value => t('.create')}

%table.data.box
  %thead
    %tr
      %th= t '.deployment'
      %th= t '.description'
      %th= t '.status'
      %th= t '.active'
      %th= t '.parent'
      %th= t '.actions'
  %tbody
    - @list.each do |d|
      - state = d.state
      %tr
        %td= link_to d.name, deployment_path(d.id)
        %td= d.description
        %td
          .led{:class => Snapshot::STATES[state], :title=>Snapshot.state_name(state)}
        %td= link_to d.head.name, snapshot_path(d.head.id), :title=>d.head.description
        %td
          - if d.parent_id
            = link_to d.parent.name, deployment_path(d.parent_id), :title=>d.parent.description
        %td= render :partial => 'buttons', :locals => { :state=>state, :snapshot=>d.head } rescue 'buttons?'

rails/app/views/deployments/show.html.haml
- state = @deployment.state rescue Snapshot::ERROR

%h1
  = "#{@deployment.name} #{Snapshot.state_name(state)}"
  = "("
  = link_to @deployment.head.name, deployment_head_path(@deployment.id)
  = ")"

%table.plain{:width=>'100%'}
  %tr
    %td
      .led{:class => Snapshot::STATES[state], :title=>Snapshot.state_name(state)}
    %td
      = @deployment.description
    %td{:align=>'right'}
      = render :partial => 'buttons', :locals => { :state=>state, :snapshot=>@deployment.head }
  - if @deployment.parent_id
    %tr
      %td
      %td
        = t '.parent'
        = link_to @deployment.parent.name, deployment_path(@deployment.parent.id), :title=>@deployment.parent.description
      %td


.clear


%h2= t '.nodes'
= render :partial => 'nodes/index', :locals => { :nodes=>@deployment.nodes.order("name ASC") }

%h2= t '.snapshots'
= render :partial => 'snapshots/index', :locals => { :list=>@deployment.snapshots.order("id DESC") }

.clear